name: Issue Reply

on:
  issues:
    types: [opened]

jobs:
  issue-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Issue Title
        id: issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            console.log(`Issue title: ${issue.title}`);
            return { issue_title: issue.title }

      - name: Set Test Line
        run: |
          TEST_LINE=$(head -n 1 README.md)
          echo "TEST_LINE=${TEST_LINE}" >> $GITHUB_ENV

      - name: Reply to Issue
        uses: peter-evans/create-or-update-comment@v1.4.3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for creating the issue '${{ env.ISSUE_TITLE }}'. We will investigate it shortly.

            The first line of the README is: '${{ env.TEST_LINE }}'.
